###############################################################################
# wordpres fpm docker-compose
# Zerbinati Francesco
# 17/01/18
# mariadb + nginx + php-fpm + wordpress
###############################################################################

version: '2'
services:

    db:
      image: mariadb:10
      container_name: mariadb
      restart: always
      volumes:
        - ./data/mysql:/var/lib/mysql
        - ./conf/mariadb/my.cnf:/etc/mysql/conf.d/settings.cnf
        - ./conf/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"
    web-server:
      image: nginx:alpine
      restart: always
      container_name: nginx
      volumes:
        - wordpress:/var/www/html
        - ./data/wordpress/wp-content:/var/www/html/wp-content
        - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./conf/nginx/cloudflare.conf:/etc/nginx/cloudflare.conf
        - ./log/nginx/:/var/log/nginx/
        - ./conf/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
        - run_vol:/var/run
      ports:
        - "${PORT}:80"

    wordpress-php-fpm:
      build:  conf/php-fpm
      restart: always
      container_name: php-fpm
      volumes:
        - wordpress:/var/www/html
        - ./data/wordpress/wp-config.php:/var/www/html/wp-config.php
        - ./data/wordpress/wp-content:/var/www/html/wp-content
        - ./data/wordpress/phpinfo.php:/var/www/html/phpinfo.php
        - ./conf/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
        - ./conf/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf

volumes:
  wordpress:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs